-- MySQL Script generated by MySQL Workbench
-- Sat Jul 22 17:21:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`Estado` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`Municipio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Estado_ID` INT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `CodIBGE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Estado_ID_idx` (`Estado_ID` ASC) VISIBLE,
  CONSTRAINT `Estado_ID`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `loja`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`Cliente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `Celular` CHAR(11) NOT NULL,
  `EndLogradouro` VARCHAR(100) NOT NULL,
  `EndNumero` VARCHAR(10) NOT NULL,
  `EndMunicipio` VARCHAR(100) NOT NULL,
  `EndCEP` CHAR(8) NULL,
  `Municipio_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Municipio_ID_idx` (`Municipio_ID` ASC) VISIBLE,
  CONSTRAINT `Municipio_ID`
    FOREIGN KEY (`Municipio_ID`)
    REFERENCES `loja`.`Municipio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`ContaReceber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`ContaReceber` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Cliente_ID` INT NULL,
  `FaturaVendaID` INT NULL,
  `DataConta` DATE NOT NULL,
  `DataVencimento` DATE NOT NULL,
  `Valor` DECIMAL(18,2) NOT NULL,
  `Situação` ENUM('1', '2', '3') NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Cliente_ID_idx` (`Cliente_ID` ASC) VISIBLE,
  CONSTRAINT `Cliente_ID`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `loja`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
